version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tennis_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tennis_network

  web:
    build: .
    container_name: tennis_app
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
    networks:
      - tennis_network
    volumes:
      - ./pagine_web:/app/pagine_web
      - ./static:/app/static

networks:
  tennis_network:
    driver: bridge

volumes:
  mongodb_data: